library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LandingPage.as_view(), name='landing-page'),
    path('management/', include('management.urls')),
    path('student/', include('student.urls')),
    path('librarian/', include('librarian.urls'))
]

lms_22.0.1/library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LandingPage.as_view(), name='landing-page'),
    path('management/', include('management.urls')),
    path('student/', include('student.urls')),
    path('librarian/', include('librarian.urls'))
]

lms_22.0.1/management/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ManagementView.as_view(), name='management-login'),
    path('login', views.ManagementLoginView.as_view(), name='management-home'),
    path('home',views.loading_page, name='home-navigation'),
    #path('home', views.home, name='home'),
    path('change-mode',views.loading_change_mode_management_home, name='management-change-mode'),
    path('changing-mode', views.change_mode_in_home, name='management-changing-mode'),
    path('add-new-book', views.add_new_book_navigation, name='add-new-book'),
    path('add-book',views.add_new_book),
    path('search',views.search_for_books),
    path('logout',views.logout_view, name='logout'),
    path('loading-student-details', views.loading_student_details, name='m-loading-student-details'),
    path('student-details', views.get_student_details, name='m-student-details'),
    path('student-information/<slug>', views.get_student_wise_information, name='student-wise-details'),
    #path('delete/<slug>', views.delete_book, name='delete-book'),
    path('deleting-book', views.delete_book, name='delete-book'),
    path('update-<slug>', views.update_book_navigation, name='update-navigation'),
    path('update-book/<slug>', views.update_book_information, name='update-book'),
    path('loading-librarian-details', views.loading_librarian_details, name='m-loading-librarian-details'),
    path('librarian-details', views.get_librarian_details, name='m-librarian-details'),
    path('loading-back-to-home', views.loading_back_to_home_staff, name='m-back-to-home'),
    path('librarian-information/<slug>', views.get_librarian_wise_information, name='librarian-wise-details'),
    path('book-details/<slug>', views.get_book_details, name='management-book-details'),
    path('search-students', views.students_filtering),
    path('search-librarians', views.librarians_filtering),
    path('md/login', views.mode_change_loginPage, name='mode-change-for-login')
]

management/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ManagementView.as_view(), name='management-login'),
    path('login', views.ManagementLoginView.as_view(), name='management-home'),
    path('home',views.loading_page, name='home-navigation'),
    #path('home', views.home, name='home'),
    path('change-mode',views.loading_change_mode_management_home, name='management-change-mode'),
    path('changing-mode', views.change_mode_in_home, name='management-changing-mode'),
    path('add-new-book', views.add_new_book_navigation, name='add-new-book'),
    path('add-book',views.add_new_book),
    path('search',views.search_for_books),
    path('logout',views.logout_view, name='logout'),
    path('loading-student-details', views.loading_student_details, name='m-loading-student-details'),
    path('student-details', views.get_student_details, name='m-student-details'),
    path('student-information/<slug>', views.get_student_wise_information, name='student-wise-details'),
    #path('delete/<slug>', views.delete_book, name='delete-book'),
    path('deleting-book', views.delete_book, name='delete-book'),
    path('update-<slug>', views.update_book_navigation, name='update-navigation'),
    path('update-book/<slug>', views.update_book_information, name='update-book'),
    path('loading-librarian-details', views.loading_librarian_details, name='m-loading-librarian-details'),
    path('librarian-details', views.get_librarian_details, name='m-librarian-details'),
    path('loading-back-to-home', views.loading_back_to_home_staff, name='m-back-to-home'),
    path('librarian-information/<slug>', views.get_librarian_wise_information, name='librarian-wise-details'),
    path('book-details/<slug>', views.get_book_details, name='management-book-details'),
    path('search-students', views.students_filtering),
    path('search-librarians', views.librarians_filtering),
    path('md/login', views.mode_change_loginPage, name='mode-change-for-login')
]

library - Copy/lms_22.0.1/management/models.py
from django.db import models

# Create your models here.

class Management(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    count = models.IntegerField(default=5)
    mode = models.CharField(max_length=20, default='Dark Mode')

class Books(models.Model):
    title = models.CharField(max_length=20)
    author = models.CharField(max_length=20)
    CHOICES = (
        (0,'Select Category'),
        ('bachelor-of-arts','Bachelor of Arts'),
        ('bba/bms','BMS/BBA'),
        ('btech-bachlor-of-engg./tech','Bachelor of Engg./Tech' ),
        ('bachelor-of-commerce','Bachelor of Commerce' ),
        ('bachelor-of-law','Bachelor of Law'),
        ('mbbs-bachelor-of-medicine','Bachelor of Medicine' ),
        ('bachelor-of-science','Bachelor of Science'),
        ('intermediate','Intermediate'),
        ('ssc-10th-standard','10th Standard')
    )
    category = models.CharField(max_length=30, choices=CHOICES, default=0)
    upload_date = models.CharField(max_length=20)
    description = models.CharField(max_length=50)
    available_count = models.IntegerField(default=0)
    location = models.CharField(max_length=30)

# Student books information
class StudentBooksInfo(models.Model):
    book_name = models.CharField(max_length=40)
    librarian_email = models.CharField(max_length=40)
    student_email = models.CharField(max_length=40)
    status = models.CharField(max_length=40)
    requested_date = models.DateField()
    approved_date = models.DateField()
    return_date = models.DateField()
    return_approved_date = models.DateField()

library - Copy/lms_22.0.1/management/forms.py
from django.forms import ModelForm, PasswordInput, Textarea
from management.models import Management,Books

class ManagementForm(ModelForm):
    class Meta:
        model = Management
        fields = ['username','password']
        labels = {
            "username":"Username",
            "password":"Password"
        }
        widgets = {
            'password':PasswordInput()
        }

class AddNewBookForm(ModelForm):
    class Meta:
        model = Books
        fields = ['title','author','category','description','available_count','location']
        labels = {
            'title':'Enter book title',
            'author':'Enter book author name',
            'category':'',
            'description':'Enter book description',
            'available_count':'Enter no.of books ',
            'location':'Book Location'
        }
        widgets = {
            'description': Textarea()
        }

library - Copy/lms_22.0.1/management/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from datetime import date
import logging

from . import actions
from library import messages
from .forms import ManagementForm, AddNewBookForm
from .models import Management, Books, StudentBooksInfo
from student.models import Student_Registration
from librarian.models import LibrarianRegistration

logging.basicConfig(level=logging.DEBUG, filename='logs/managementDEBUG.log', filemode='w', format='%(asctime)s %(name)s - %(levelname)s - %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
# Create your views here.

# mode change in login page
def mode_change_loginPage(request):
    if request.method=='POST':
        mode = request.POST['mode1']
        management = Management.objects.all()[0]
        management.mode=mode
        management.save()
        return HttpResponseRedirect('/management')
    else:
        return HttpResponse('incorrect method')

# navigate to login page
def navigate_to_login_page(request, msg, user):
    form = ManagementForm()
    dbuser = Management.objects.all()[0]
    return render(request, 'management/managementLogin.html', {
        'title': 'management login',
        'forms': form,
        'msg': msg,
        'mode': dbuser.mode,
        'user':user
    })

# Login page
class ManagementView(View):
    
    def get(self, request):
        logging.info(' trying to load login page for Management login')
        form = ManagementForm()
        management_mode = Management.objects.all()[0]
        logging.info('Successfully loaded...')
        return render(request, 'management/managementLogin.html',{
            'forms':form,
            'title':'management login',
            'msg':'none',
            'mode':management_mode.mode
        })

# Login check
class ManagementLoginView(FormView):

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        try:
            dbuser = Management.objects.get(username=username)
            logging.info(f'{username} trying to login...')
            count = int(dbuser.count)
            logging.info('Checking login limit for Management login')
            if count >= 1 and count <= 5:
                if username == dbuser.username and password == dbuser.password:
                    user = authenticate(username=username, password=password)
                    logging.info('Authenticating Management user')
                    if user is not None:
                        login(request, user)
                        logging.info('Checking login....')
                        dbuser.count = 5
                        dbuser.save()
                        logging.info('Done, Successfully logged in...')
                        # return redirect('/management/home')
                        return render(request, 'management/loading_page.html', {
                            'username': user,
                            'formtype': 'user-login'
                        })
                    else:
                        new_user = User.objects.create_user(username=username, email=username + '@mail.com',
                                                            password=password)
                        new_user.set_password(password)
                        new_user.save()
                        login(request, new_user)
                        logging.info('Checking login....')
                        dbuser.count = 5
                        dbuser.save()
                        logging.info('Done, Successfully logged in...')
                        # return redirect('/management/home')
                        return render(request, 'management/loading_page.html', {
                            'username': new_user,
                            'formtype': 'user-login'
                        })
                else:
                    logging.warning(f'{username} entered credentials are not matching with db user...')
                    dbuser.count = dbuser.count - 1
                    dbuser.save()
                    return navigate_to_login_page(request, 'Enter valid Password', dbuser)
            else:
                logging.warning(f'{username} exceeded limit of incorrect credentials...')
                return navigate_to_login_page(request, 'Account locked, Please contact DB admin', dbuser)
        except:
            logging.warning(f'{username} entered credentials are not matching for authentication...')
            return navigate_to_login_page(request, 'Enter valid Username', 'none')

# loading page view for home page
@login_required(login_url='/management')
def loading_page(request):
    if request.method=='POST':
        username = str(request.POST['username'])
        print(username)
        user = Management.objects.get(username=username)
        wish = messages.wish()
        books = Books.objects.all()
        return render(request, 'management/managementHome.html',{
            'wishes': wish,
            'books': books,
            'mode': user.mode,
            'user':user
        })
    else:
        return HttpResponse('something went wrong')


# change mode in management home
@login_required(login_url='/management')
def loading_change_mode_management_home(request):
    if request.method == 'POST':
        mode = request.POST['mode']
        username = request.POST['username']
        user = Management.objects.get(username=username)
        return render(request, 'management/loading_page.html', {
            'username': user,
            'mode':mode,
            'formtype': 'change-mode-home'
        })

    else:
        return HttpResponse('something went wrong')

# change mode in home
@login_required(login_url='/management')
def change_mode_in_home(request):
    if request.method=='POST':
        username = request.POST['username']
        mode = request.POST['mode']
        user = Management.objects.get(username=username)
        user.mode = mode
        user.save()
        return render(request, 'management/loading_page.html', {
            'username': user,
            'formtype': 'user-login'
        })
    else:
        return HttpResponse('something went wrong')


#Add new book
@login_required(login_url='/management')
def add_new_book_navigation(request):
    try:
        form = AddNewBookForm()
        logging.info('Navigating to Add new book page')
        return render(request, 'management/updateAddM.html',{
        'forms':form,
        'title':'add new book',
        'message':''
        })
    except:
        logging.debug('error occurred at line 113...')
        return HttpResponse('something went wrong')

#Add book to database
@login_required(login_url='/management')
def add_new_book(request):

    if request.method=='POST':
        book_title = request.POST['title']
        book_author = request.POST['author']
        book_category = request.POST['category']
        book_description = request.POST['description']
        book_count = request.POST['available_count']
        logging.info(f'book details entered: book name: {book_title}')
        today = date.today()
        book_upload_date = today.strftime("%d/%m/%Y")
        try:
            bookname = Books.objects.get(title=book_title)
            if bookname:
                logging.warning(f'{book_title} :book already exists in database...')
                form = AddNewBookForm()
                logging.info('Navigating to Add new book page')
                return render(request, 'management/updateAddM.html', {
                    'forms': form,
                    'title': 'add new book',
                    'message': 'Book name already exists, Please try again'
                })
        except:
            logging.info(f'trying to store {book_title} details in database...')
            book = Books(
                title=book_title,
                author=book_author,
                category=book_category,
                description=book_description,
                available_count=book_count,
                upload_date=book_upload_date
            )
            book.save()
            logging.info(f'{book_title}: Successfully stored in database')
            form = AddNewBookForm()
            return render(request, 'management/updateAddM.html', {
                'forms': form,
                'title': 'add new book',
                'message': 'Successfully added new book'
            })

    else:
        logging.warning('tried get method instead post...')
        return HttpResponse('incorrect method type')

#search for books
@login_required(login_url='/management')
def search_for_books(request):
    if request.method=='GET':
        try:
            username = request.GET['search_username']
            category = request.GET['select_search']
            search_text = request.GET['search_text']
            books = actions.search_book(category, search_text)
            wish = messages.wish()
            user = Management.objects.get(username=username)
            logging.info('User trying to search of books...')
            return render(request, 'management/ManagementHome.html', {
                'wishes': wish,
                'books': books,
                'mode': user.mode,
                'user':user
        })
        except:
            logging.debug('error occurred at line 170...')
            return HttpResponse('something went wrong')
    else:
        return HttpResponse('incorrect method sent through form')

# for logout
def logout_view(request):
    try:
        logging.info('logging out..')
        logout(request)
        logging.info('User logged out from portal...')
        return redirect('/management')

library - Copy/lms_22.0.1/management/templates/management/form.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{ title|title }}
{% endblock %}

{% block css_effect %}
    <link rel="stylesheet" href="{% static 'management/form.css' %}">
{% endblock %}

{% block body_content %}

{% if title == "management login" %}
<section style="height: 100%;">
    <a href="{% url 'landing-page' %}"><img src="{% static 'images/ineuron-logo.png' %}" alt="Ineuron icon"></a>
    <div class="messages" id="error_class">
        <span id="error">{{ message }}</span>
    </div>
    <form action="login" method="post" class="form-group">
        {% csrf_token %}
        <h2>{{ title|title }}</h2>

        {% for form in forms %}
            {{ form.label_tag }}
            {{ form }}
        {% endfor %}

        <p>If you forget credentials, Please reach out to <br> your Database Admin..</p>
        <button type="submit" class="btn btn-success">Login</button>
    </form>
</section>
{% elif title == 'add new book' %}
<section >
    <a href="{% url 'landing-page' %}"><img src="{% static 'images/ineuron-logo.png' %}" alt="Ineuron icon"></a>
    <a href="" class="back_home">Back to home</a>
    <div class="messages" id="error_class">
        <span id="error">{{ msg }}</span>
    </div>

    <form action="add-book" method="post" class="form-group">
        {% csrf_token %}
        <h2>{{ title|title }}</h2>

        {% for form in forms %}
            {{ form.label_tag }}
            {{ form }}
        {% endfor %}

        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</section>
{% else %}
<section >

</section>

{% endif %}

{% if title == "management login" %}
<script>

    window.onload = function loadInputClass(){

        // for login form 

        let adminUsername = document.getElementById('id_username')
        adminUsername.classList.add('form-control')

        let adminPassword = document.getElementById('id_password')
        adminPassword.classList.add('form-control')

        // error handling
        let error_class = document.getElementById('error_class')
        let error = document.getElementById('error').innerText
        if(error=='Enter valid credentials' || error=='Account locked, Please contact DB admin'){
            error_class.classList.add('error_invalid')
        }
    }
</script>

{% else %}
<script>
    window.onload = function loadStyle(){

        // for add new book form

        // error handling
        let error_class = document.getElementById('error_class')
        let error = document.getElementById('error').innerText
        if(error=='Successfully added new book'){
            error_class.classList.add('error_success')
        } else if(error=='Book name already exists'){
            error_class.classList.add('error_invalid')
        }

        // input styles
        let bookTitle = document.getElementById('id_title')
        bookTitle.classList.add('form-control')
        bookTitle.innerHTML=""

        let bookAuthor = document.getElementById('id_author')
        bookAuthor.classList.add('form-control')
        bookAuthor.innerHTML=""

        let bookCategory = document.getElementById('id_category')
        bookCategory.classList.add('form-select')

        let bookDescription = document.getElementById('id_description')
        bookDescription.classList.add('form-control')
        bookDescription.innerHTML=""

        let bookCount = document.getElementById('id_available_count')
        bookCount.classList.add('form-control')
        bookCount.innerHTML=""

    }
</script>
{% endif %}

{% endblock %}

library - Copy/lms_22.0.1/management/templates/management/update.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{ title|title }}
{% endblock %}

{% block css_effect %}
    <link rel="stylesheet" href="{% static 'management/form.css' %}">
{% endblock %}

{% block body_content %}

<section>

<a href="{% url 'landing-page' %}"><img src="{% static 'images/ineuron-logo.png' %}" alt="Ineuron icon"></a>
<a href="" class="back_home">Back to home</a>
<div class="messages" id="error_class">
    <span id="error">{{ message }}</span>
</div>

{% if title == 'update book details' %}

<form action="{% url 'update-book' book.id %}" method="post">
    {% csrf_token %}
    <h2>{{title|title}}</h2>
    <label for="id_title">Update book name:</label>
    <input type="text" class="form-control" value="{{ book.title }}" name="title" id="id_title">
    <label for="id_author">Update book author:</label>
    <input type="text" class="form-control" value="{{ book.author }}" name="author" id="id_author">

    {% if book.category == 'bachelor-of-arts' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Arts</label>
    {% elif book.category == 'bba/bms' %}
        <label for="id_category" style="color: green;">Selected: BBA/BMS</label>
    {% elif book.category == 'btech-bachelor-of-engg./tech' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Engg./Tech</label>
    {% elif book.category == 'bachelor-of-commerce' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Commerce</label>
    {% elif book.category == 'mbbs-bachelor-of-medicine' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Medicine</label>
    {% elif book.category == 'bachelor-of-science' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Science</label>
    {% elif book.category == 'intermediate' %}
        <label for="id_category" style="color: green;">Selected: Intermediate</label>
    {% elif book.category == 'ssc-10th-standard' %}
        <label for="id_category" style="color: green;">Selected: 10th-Standard</label>
    {% else %}
        <label for="id_category" style="color: green;">No category selected</label>
    {% endif %}

    <select name="category" id="id_category" class="form-select">
        <option value=0>select Category</option>
        {% for keys, items in options.items %}
        <option value="{{ keys }}">{{ items }}</option>
        {% endfor %}
    </select>
    <label for="id_description">Update book description:</label>
    <textarea name="description" class="form-control" id="id_description" cols="30" rows="10">{{ book.description }}</textarea>
    <label for="id_available_count">Update book available count:</label>
    <input type="number" class="form-control" value="{{ book.available_count }}" name="available_count" id="id_available_count">
    <label for="id_location">Location of book:</label>
    <input type="text" class="form-control" value="{{ book.location }}" name="location" id="id_location">
    <button type="submit" class="btn btn-success">Update</button>
</form>
    
{% endif %}
</section>

{% endblock %}

library - Copy/lms_22.0.1/management/templates/management/updateAddM.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{ title|title }}
{% endblock %}

{% block css_effect %}
    <link rel="stylesheet" href="{% static 'management/updateAddM.css' %}">
{% endblock %}

{% block body_content %}

    <nav>
        <a href="{% url 'landing-page' %}"><img src="{% static 'images/ineuron-logo-white.png' %}" alt="icon"></a>
    </nav>

    {% if title == 'update book details' %}

    <div class="heading">
        <h2>Update Book</h2>
    </div>

    <form action="{% url 'update-book' book.id %}" method="post">
        {% csrf_token %}
        <div class="content">
        
            <div class="inputStyle">
                <label for="bookName">Book Name:</label>
                <input type="text" id="bookName" name="update_title" value="{{book.title}}" class="form-control">
            </div>
            <div class="inputStyle">
                <label for="bookAuthor">Book Author:</label>
                <input type="text" id="bookAuthor" name="update_author" value="{{book.author}}" class="form-control">
            </div>
            <div class="inputStyle">
                <label for="bookCategory">Book Category: </label>
                {% if book.category == 'bachelor-of-arts' %}
                <label for="bookCategory">Selected: Bachelor of Arts</label><br>
                {% elif book.category == 'bba/bms' %}
                <label for="bookCategory">Selected: BBA/BMS</label><br>
                {% elif book.category == 'btech-bachelor-of-engg./tech' %}
                <label for="bookCategory">Selected: Bachelor of Engg./Tech</label><br>
                {% elif book.category == 'bachelor-of-commerce' %}
                <label for="bookCategory">Selected: Bachelor of Commerce</label><br>
                {% elif book.category == 'mbbs-bachelor-of-medicine' %}
                <label for="bookCategory">Selected: Bachelor of Medicine</label><br>
                {% elif book.category == 'bachelor-of-science' %}
                <label for="bookCategory">Selected: Bachelor of Science</label><br>
                {% elif book.category == 'intermediate' %}
                <label for="bookCategory">Selected: Intermediate</label><br>
                {% elif book.category == 'ssc-10th-standard' %}
                <label for="bookCategory">Selected: 10th-Standard</label><br>
                {% elif book.category == 'bachelor-of-law' %}
                <label for="bookCategory">Selected: Bachelor of Law</label><br>
                {% else %}
                <label for="bookCategory">No category selected</label><br>
                {% endif %}

                <select name="update_category" id="bookCategory" class="form-select">
                    <option value="0">select option</option>
                    {% for keys, items in options.items %}
                    <option value="{{ keys }}">{{ items }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="inputStyle">
                <label for="bookDescription">Book description:</label>
                <textarea type="text" name="update_description" id="bookDescription" class="form-control">{{book.description}}</textarea>
            </div>

            <div class="inputStyle">
                <label for="bookCount">Books available count:</label>
                <input type="number" name="update_count" id="bookCount" value="{{ book.available_count }}" class="form-control">
            </div>

            <div class="inputStyle">
                <label for="bookLocation">Book Location:</label>
                <input type="text" name="update_location" id="bookLocation" value="{{ book.location }}" class="form-control">
            </div>

            <div class="inputStyle" style="margin-top: 3em;">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>  
    </form>
    {% elif title == 'add new book' %}

    <div class="heading">
        <h2>Add New Book</h2>
    </div>

    <form action="add-book" method="post">
        {% csrf_token %}
        <div class="content">
            {% for form in forms %}
            <div class="inputStyle">
                {{ form.label_tag }}
                {{ form }}
            </div>
            {% endfor %}
            <div class="inputStyle" style="margin-top: 3em;">
                <button type="submit" class="btn btn-success">Add Book</button>
            </div>
        </div>
    </form>
    
    {% endif %}

    

    <div class="message">
        <div class="messages">
            <h5>{{message}}</h5>
            <div>
                <button class="btn btn-success" onclick="closePopup()">Close</button>
            </div>
            
        </div>
    </div>
    
<script>

    window.onload = ()=>{
        let msg = document.querySelector('h5').innerText
        openPopup(msg)
        loadFormAddStyles()
    }

    // close popup
    function closePopup(){
        document.querySelector('.message').style.display = 'none'
    }

    // open popup
    function openPopup(msg){
        if(msg.length>0){
            document.querySelector('.message').style.display = 'block'  
        }
        else{
            document.querySelector('.message').style.display = 'none'  
        }
    }

    // load form input styles to inputs
    function loadFormAddStyles(){
        document.querySelector('#id_title').classList.add('form-control')
        document.querySelector('#id_author').classList.add('form-control')

        let category = document.querySelector('#id_category')
        category.classList.add('form-select')
        category.style.margin = '1.4em'

        let description = document.querySelector('#id_description')
        description.classList.add('form-control')
        description.style.height = '5em'


        document.querySelector('#id_available_count').classList.add('form-control')
        document.querySelector('#id_location').classList.add('form-control')
    }

</script>

{% endblock %}