library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LandingPage.as_view(), name='landing-page'),
    path('management/', include('management.urls')),
    path('student/', include('student.urls')),
    path('librarian/', include('librarian.urls'))
]

lms_22.0.1/library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LandingPage.as_view(), name='landing-page'),
    path('management/', include('management.urls')),
    path('student/', include('student.urls')),
    path('librarian/', include('librarian.urls'))
]

lms_22.0.1/student/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.student_login_navigation, name='student-login'),
    path('new-account', views.student_registration_navigation, name='student-registration'),
    path('registration', views.register_new_student),
    path('home', views.student_home, name='student-home'),
    path('logout', views.logout_view, name='student-logout'),
    path('search/<slug>', views.search_for_books, name='search'),
    path('books/<slug>', views.get_book_details, name='student-book-details'),
    path('librarian-details', views.librarian_details, name='student-librarian-details'),
    path('student-books', views.student_collections, name='student-collections'),
    path('update', views.student_update_navigation, name='student-update-navigation'),
    path('updated', views.update_student),
    path('preview-book', views.preview_book_details, name='preview-book'),
    path('borrow-book', views.borrow_book_for_student, name='student-borrow-book'),
    path('task-status', views.task_wise_information, name='student-task-status'),
    path('return-book', views.return_book, name='student-return-book'),
]

student/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.student_login_navigation, name='student-login'),
    path('new-account', views.student_registration_navigation, name='student-registration'),
    path('registration', views.register_new_student),
    path('home', views.student_home, name='student-home'),
    path('logout', views.logout_view, name='student-logout'),
    path('search/<slug>', views.search_for_books, name='search'),
    path('books/<slug>', views.get_book_details, name='student-book-details'),
    path('librarian-details', views.librarian_details, name='student-librarian-details'),
    path('student-books', views.student_collections, name='student-collections'),
    path('update', views.student_update_navigation, name='student-update-navigation'),
    path('updated', views.update_student),
    path('preview-book', views.preview_book_details, name='preview-book'),
    path('borrow-book', views.borrow_book_for_student, name='student-borrow-book'),
    path('task-status', views.task_wise_information, name='student-task-status'),
    path('return-book', views.return_book, name='student-return-book'),
]

management/models.py
from django.db import models

# Create your models here.

class Management(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    count = models.IntegerField(default=5)
    mode = models.CharField(max_length=20, default='Dark Mode')

class Books(models.Model):
    title = models.CharField(max_length=20)
    author = models.CharField(max_length=20)
    CHOICES = (
        (0,'Select Category'),
        ('bachelor-of-arts','Bachelor of Arts'),
        ('bba/bms','BMS/BBA'),
        ('btech-bachlor-of-engg./tech','Bachelor of Engg./Tech' ),
        ('bachelor-of-commerce','Bachelor of Commerce' ),
        ('bachelor-of-law','Bachelor of Law'),
        ('mbbs-bachelor-of-medicine','Bachelor of Medicine' ),
        ('bachelor-of-science','Bachelor of Science'),
        ('intermediate','Intermediate'),
        ('ssc-10th-standard','10th Standard')
    )
    category = models.CharField(max_length=30, choices=CHOICES, default=0)
    upload_date = models.CharField(max_length=20)
    description = models.CharField(max_length=50)
    available_count = models.IntegerField(default=0)
    location = models.CharField(max_length=30)

# Student books information
class StudentBooksInfo(models.Model):
    book_name = models.CharField(max_length=40)
    librarian_email = models.CharField(max_length=40)
    student_email = models.CharField(max_length=40)
    status = models.CharField(max_length=40)
    requested_date = models.DateField()
    approved_date = models.DateField()
    return_date = models.DateField()
    return_approved_date = models.DateField()

library - Copy/lms_22.0.1/student/forms.py
from django.forms import ModelForm, PasswordInput, Textarea, EmailInput
from .models import Student_Registration

class StudentRegistrationForm(ModelForm):
    class Meta:
        model = Student_Registration
        fields = ['student_name','student_email','student_password','student_category']
        labels = {
            'student_name':'Enter your name',
            'student_email':'Enter you email address',
            'student_password':'Enter your password',
            'student_category':''
        }
        widgets = {
            'student_password':PasswordInput(),
            'student_email':EmailInput()
        }

class StudentLoginForm(ModelForm):
    class Meta:
        model = Student_Registration
        fields = ['student_email','student_password']
        labels = {
            'student_email':'Enter email address',
            'student_password':'Enter your password'
        }

        widgets = {
            'student_password':PasswordInput(),
            'student_email':EmailInput()
        }

library - Copy/student/forms.py
from django.forms import ModelForm, PasswordInput, Textarea, EmailInput
from .models import Student_Registration

class StudentRegistrationForm(ModelForm):
    class Meta:
        model = Student_Registration
        fields = ['student_name','student_email','student_password','student_category']
        labels = {
            'student_name':'Enter your name',
            'student_email':'Enter you email address',
            'student_password':'Enter your password',
            'student_category':''
        }
        widgets = {
            'student_password':PasswordInput(),
            'student_email':EmailInput()
        }

class StudentLoginForm(ModelForm):
    class Meta:
        model = Student_Registration
        fields = ['student_email','student_password']
        labels = {
            'student_email':'Enter email address',
            'student_password':'Enter your password'
        }

        widgets = {
            'student_password':PasswordInput(),
            'student_email':EmailInput()
        }

library - Copy/lms_22.0.1/student/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from datetime import date

from .forms import StudentRegistrationForm, StudentLoginForm
from .models import Student_Registration
from library import messages
from management.models import Books, StudentBooksInfo
from librarian.models import LibrarianRegistration

from . import actions

logging.basicConfig(level=logging.DEBUG, filename='logs/managementDEBUG.log', filemode='w', format='%(asctime)s %(name)s - %(levelname)s - %(message)s', datefmt='%Y-%m-%d %H:%M:%S')

# Create your views here.

#student registration navigation
def student_registration_navigation(request):
    form = StudentRegistrationForm
    logging.info('rendering student registration page')
    return render(request, 'student/form.html',{
        'forms':form,
        'title':'student registration'
    })

# student login navigation
def student_login_navigation(request):
    form = StudentLoginForm
    logging.info('rendering student login page')
    return render(request, 'student/form.html',{
        'forms':form,
        'title':'student login'
    })

"""student home page navigation ------->
def student_home_page_navigation(request,student):
    wish = messages.wish()
    student_books = actions.get_student_books(student.student_category)
    librarians = actions.get_librarian_details()
    return render(request, 'student/home.html', {
        'student': student,
        'wishes': wish,
        'books': student_books,
        'id': student.id,
        'librarians': librarians
    })"""

"""student login page navigation ---------->
def student_login_page_navigation(request, msg):
    form = StudentLoginForm()
    return render(request, 'student/form.html', {
        'title': 'student login',
        'forms': form,
        'message': msg
    })"""

# student home navigation
@login_required(login_url='student-login')
def student_home_page(request):
    pass

# student login check
def student_home(request):
    logging.info('rendering student login')
    if request.method=='POST':
        student_email = request.POST['student_email']
        student_password = request.POST['student_password']
        logging.info(f'{student_email} is trying to login')
        try:
            student = Student_Registration.objects.get(student_email=student_email)
            student_count = int(student.student_login_count)

            if student.student_status == 'unblock':
                if student_count > 0 and student_count <= 5:
                    if student_email == student.student_email and student_password == student.student_password:
                        user = authenticate(username=student_email, password=student_password)
                        login(request, user)
                        student.student_login_count = 5
                        student.save()
                        logging.info('successfully logged in')
                        """student_books = actions.get_student_books(student.student_category)
                        wish = messages.wish()
                        librarians = actions.get_librarian_details()
                        return render(request, 'student/home.html', {
                            'student': student,
                            'wishes': wish,
                            'books': student_books,
                            'id': student.id,
                            'librarians': librarians
                        })"""
                        return actions.student_home_page_navigation(request, student)

                    else:
                        student.student_login_count = student.student_login_count - 1
                        student.save()
                        # form = StudentLoginForm()
                        logging.warning('Invalid credentials are entered')
                        """return render(request, 'student/form.html', {
                            'title': 'student login',
                            'forms': form,
                            'message': 'Invalid Credentials...'
                        })"""
                        #return student_login_page_navigation(request, 'Invalid Credentials...')
                        return actions.student_login_page_navigation(request, 'Invalid Credentials...')
                else:
                    # form = StudentLoginForm()
                    logging.warning('login limit exceeded to maximum')
                    """return render(request, 'student/form.html', {
                        'title': 'student login',
                        'forms': form,
                        'message': 'Limited exceeded, Please contact Librarian...'
                    })"""
                    #return student_login_page_navigation(request, 'Limited exceeded, Please contact Librarian...')
                    return actions.student_login_page_navigation(request, 'Limit exceeded, Please contact Librarian...')
            else:
                # form = StudentLoginForm()
                logging.warning('your account blocked')
                """"return render(request, 'student/form.html', {
                    'title': 'student login',
                    'forms': form,
                    'message': 'Your account blocked, Please check with Librarain...'
                })"""
                #return student_login_page_navigation(request, 'Your account blocked, Please check with Librarain...')
                return actions.student_login_page_navigation(request, 'Your account blocked, Please check with Librarian...')
        except:
            return student_login_page_navigation(request, f'{student_email} not registered with us...')
    else:
        logging.debug('get method used')
        return HttpResponse('incorrect method used')

# register new student
def register_new_student(request):
    logging.info('trying to register new student')
    if request.method=='POST':
        student_name = request.POST['student_name']
        student_password = request.POST['student_password']
        student_email = request.POST['student_email']
        student_category = request.POST['student_category']
        today = date.today()
        student_registration_date = today.strftime("%d/%m/%Y")
        try:
            check_email = Student_Registration.objects.filter(student_email=student_email)

            if check_email:
                form = StudentRegistrationForm()
                logging.info(f'{student_email} are in use')
                return render(request, 'student/form.html',{
                    'title':'student registration',
                    'forms':form,
                    'message':'Email already exists,'
                })
            else:
                student = Student_Registration(
                    student_name=student_name,
                    student_email=student_email,
                    student_password=student_password,
                    student_category=student_category,
                    student_registration_date=student_registration_date
                )
                student.save()
                new_user = User.objects.create_user(username=student_email, email=student_email,
                                                    password=student_password)
                new_user.set_password(student_password)
                new_user.save()
                logging.info(f'successfully created new account for email: {student_email}')
                form = StudentLoginForm()
                return render(request, 'student/form.html', {
                    'title': 'student login',
                    'forms': form,
                    'message': 'Successfully created account, login here'
                })
        except:
            student = Student_Registration(
                student_name=student_name,
                student_email=student_email,
                student_password=student_password,
                student_category=student_category,
                student_registration_date=student_registration_date
            )
            student.save()
            new_user = User.objects.create_user(username=student_name, email=student_email, password=student_password)
            new_user.set_password(student_password)
            new_user.save()
            logging.info(f'successfully created new account for email: {student_email}')
            form = StudentLoginForm()
            return render(request, 'student/form.html', {
                'title': 'student login',
                'forms': form,
                'message': 'Successfully created account, login here'
            })
    else:
        logging.info('get method used')
        return HttpResponse('incorrect method used')

# for logout
def logout_view(request):
    logging.info('logging out..')
    logout(request)
    return redirect('/student')

# search for books
@login_required(login_url='student/')
def search_for_books(request, slug):
    if request.method=='POST':
        student = Student_Registration.objects.get(id=slug)
        category = request.POST['select_search']
        text = request.POST['search_input']
        search_result = actions.search_books(category, text, student)
        wish = messages.wish()
        librarians = actions.get_librarian_details()
        book_names, diff_days = actions.student_notifications(student)
        return render(request, 'student/home.html',{
            'student': student,
            'wishes': wish,
            'books': search_result,
            'librarians':librarians,
            'book_names':book_names,
            'diff_days':diff_days
        })
    else:
        return HttpResponse('incorrect method used')

# book details
@login_required(login_url='student/')
def get_book_details(request,slug):

library - Copy/student/templates/student/details.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{ title|title }}
{% endblock %}

{% block css_effect %}
    <link rel="stylesheet" href="{% static 'management/details.css' %}">
{% endblock %}

{% block body_content %}

    <section>
        <a href="{% url 'landing-page' %}"><img src="{% static 'images/ineuron-logo.png' %}" alt="Ineuron icon"></a>        

        {% if title == 'book details' %}
        <div class="details">
            <h1>Book Information</h1>
            <h4><b><u>Book ID:</u></b> &nbsp; {{ book.id }}</h4>
            <h4><b><u>Book Name:</u></b> &nbsp; {{ book.title|title }}</h4>
            <h4><b><u>Book Author:</u></b> &nbsp; {{ book.author }}</h4>

            {% if book.category == 'bachelor-of-arts' %}
                <h4><b><u>Category:</u></b> &nbsp; Bachelor of Arts</h4>
            {% elif book.category == 'bba/bms' %}
                <h4><b><u>Category:</u></b> &nbsp; BBA/BMS</h4>
            {% elif book.category == 'btech-bachlor-of-engg./tech' %}
                <h4><b><u>Category:</u></b> &nbsp; Bachelor of Engg./Tech</h4>
            {% elif book.category == 'bachelor-of-commerce' %}
                <h4><b><u>Category:</u></b> &nbsp; Bachelor of Commerce</h4>
            {% elif book.category == 'intermediate' %}
                <h4><b><u>Category:</u></b> &nbsp; Intermediate</h4>
            {% elif book.category == 'bachelor-of-law' %}
                <h4><b><u>Category:</u></b> &nbsp; Bachelor of Law</h4>
            {% elif book.category == 'mbbs-bachelor-of-medicine' %}
                <h4><b><u>Category:</u></b> &nbsp; Bachelor of Medicine</h4>
            {% elif book.category == 'bachelor-of-science' %}
                <h4><b><u>Category:</u></b> &nbsp; Bachelor of Science</h4>
            {% elif book.category == 'ssc-10th-standard' %}
                <h4><b><u>Category:</u></b> &nbsp; 10th Standard</h4>
            {% else %}
                <h4><b><u>Category:</u></b> &nbsp; No category selected</h4>
            {% endif %}

            <h4><b><u>Description:</u></b> &nbsp; <p>{{ book.description }}</p></h4>
            <h4><b><u>Book registration date:</u></b> &nbsp; {{ book.upload_date }}</h4>
            <h4><b><u>Available Count:</u></b> &nbsp; {{ book.available_count }}</h4>
        </div> 

    {% elif title == 'borrow book' %}
    <div class="error_message1">
        <span>{{ error_message }}</span>
    </div>
    <div class="success_message1">
        <span>{{ success_message }}</span>
    </div>

    <div class="details">
        <h1>Preview Book details:</h1>
        <h4 style="font-weight: bold; color: rgb(23, 138, 48);">Hello {{ student.student_name }}, Please preview your book details...</h4>
        <h4><b><u>Book ID:</u></b> &nbsp; {{ book.id }}</h4>
        <h4><b><u>Book Name:</u></b> &nbsp; {{ book.title|title }}</h4>
        <h4><b><u>Book Author:</u></b> &nbsp; {{ book.author }}</h4>
        <h4><b><u>Book Description:</u></b> &nbsp; <br> {{ book.description }}</h4>
        <h4><b><u>Available books:</u></b> &nbsp; {{ book.available_count }}</h4>
        <form action="{% url 'student-borrow-book' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="bookid" value={{book.id}}>
            <input type="hidden" name="studentid" value={{student.student_email}}>
            
            {% if msg == 'remove' %}
                
            {% else %}
            <select name="librarianid" id="librarianid" class="form-select">
                <option value=0>Select Librarian</option>
                {% for librarian in librarians %}
                    <option value={{librarian.librarian_email}}>{{librarian.librarian_name}}</option>
                {% endfor %}
            </select><br>
            <button type="submit">Borrow</button>
            {% endif %}
        </form>
    </div>
    {% elif title == 'book status' %}
    <div class="details">
        <h1>Request Status information:</h1>
        <h4 style="font-weight: bold; color: rgb(23, 138, 48);">Hello {{ student.student_name }}, Please check your request status...</h4>
        <h4><b><u>ID:</u></b> &nbsp; {{ task.id }}</h4>
        <h4><b><u>Librarian Email:</u></b> &nbsp; {{ task.librarian_email }}</h4>
        <h4><b><u>Requested Date:</u></b> &nbsp; {{ task.requested_date }}</h4>

        {% if task.requested_date == task.return_date and task.status != 'return accepted' %}
            <h4><b><u>Approved Date:</u></b> &nbsp; ----------</h4>
            <h4><b><u>Return Date:</u></b> &nbsp; -----------</h4>
        {% else %}
            <h4><b><u>Approved Date:</u></b> &nbsp; {{ task.approved_date }}</h4>
            <h4><b><u>Return Date:</u></b> &nbsp; {{ task.return_date }}</h4>
        {% endif %}

        {% if task.status == 'requested' %}
            <h4><b><u>Status:</u></b> &nbsp; <b style="color: rgb(156, 146, 31);">{{ task.status|title }}</b></h4>
            <h4>Your request not approved by <b>{{ task.librarian_email }}</b> its still in request status...</h4>
        {% elif task.status == 'approved' %}
            <h4><b><u>Status:</u></b> &nbsp; <b style="color: rgb(19, 119, 33);">{{ task.status|title }}</b></h4>
            <h4>Your request approved by <b>{{ task.librarian_email }}</b>, Please find return date above...</h4>
        {% elif task.status == 'return request' %}
            <h4><b><u>Status:</u></b> &nbsp; <b style="color: rgb(158, 147, 29);">{{ task.status|title }}</b></h4>
            <h4>Your return request not approved by <b>{{ task.librarian_email }}</b>, Please try to reach librarian asap. Else you will be blocked...</h4>
        {% elif task.status == 'return accepted' %}
            <h4><b><u>Status:</u></b> &nbsp; <b style="color: rgb(36, 133, 33);">{{ task.status|title }}</b></h4>
            <h4>Thanks for returning book on time...</h4>
        {% elif task.status == 'rejected' %}
            <h4><b><u>Status:</u></b> &nbsp; <b style="color: rgb(156, 60, 36);">{{ task.status|title }}</b></h4>
            <h4>Your request for book has been rejected by <b>{{ task.librarian_email }}</b>...</h4>
        {% else %}
            <h4><b><u>Status:</u></b> &nbsp; <b>{{ task.status|title }}</b></h4>
            <h4>No status</h4>
        {% endif %}
        
    </div>
    {% endif %}

    </section>

{% endblock %}

library - Copy/student/templates/student/form.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {{ title|title }}
{% endblock %}

{% block css_effect %}
    <link rel="stylesheet" href="{% static 'student/form.css' %}">
{% endblock %}

{% block body_content %}

{% if title == "student registration" %}
<section style="height: 130%;">
    <a href="{% url 'landing-page' %}"><img src="{% static 'images/ineuron-logo.png' %}" alt="Ineuron icon"></a>
    <div class="messages">
        {% if message == "Successfully created account, login here" %}
            <span style="background-color: rgba(120, 245, 141, 0.5); color: rgb(7, 67, 8);">{{ message }}</span>
        {% endif %}

        <span id="error">{{ message }}</span>
    </div>
    <form action="registration" method="post" class="form-group">
        {% csrf_token %}
        <h2>{{ title|title }}</h2>

        {% for form in forms %}
            {{ form.label_tag }}
            {{ form }}
        {% endfor %}

        <button type="submit" class="btn btn-success">Register</button><br>
        <a href="{% url 'student-login' %}">Already have an account, click here to login</a>
    </form>
</section>
{% elif title == 'student login' %}
<section style="height:100% ;">
    <a href="{% url 'landing-page' %}"><img src="{% static 'images/ineuron-logo.png' %}" alt="Ineuron icon"></a>
    <div class="messages" id="error_class">
        <span id="error">{{ message }}</span>
    </div>

    <form action="home" method="post" class="form-group">
        {% csrf_token %}
        <h2>{{ title|title }}</h2>

        {% for form in forms %}
            {{ form.label_tag }}
            {{ form }}
        {% endfor %}

        <button type="submit" class="btn btn-success">Login</button>
        <a href="{% url 'student-registration' %}">No account, click here for new registration</a>
    </form>
</section>
{% else %}
<section >

</section>

{% endif %}

{% if title == "student registration" %}
<script>

    window.onload = function loadInputClass(){

        // for login form

        let studentName = document.getElementById('id_student_name')
        studentName.classList.add('form-control')

        let studentPassword = document.getElementById('id_student_password')
        studentPassword.classList.add('form-control')

        let studentEmail = document.getElementById('id_student_email')
        studentEmail.classList.add('form-control')

        let studentCategory = document.getElementById('id_student_category')
        studentCategory.classList.add('form-select')
    }
</script>

{% else %}
<script>
    window.onload = function loadStyle(){

        // for add new book form

        let studentPassword = document.getElementById('id_student_password')
        studentPassword.classList.add('form-control')

        let studentEmail = document.getElementById('id_student_email')
        studentEmail.classList.add('form-control')

    }
</script>
{% endif %}

{% endblock %}

library - Copy/student/templates/student/update.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    Update profile
{% endblock %}

{% block css_effect %}
    <link rel="stylesheet" href="{% static 'management/form.css' %}">
{% endblock %}

{% block body_content %}

<section>

<a href="{% url 'landing-page' %}"><img src="{% static 'images/ineuron-logo.png' %}" alt="Ineuron icon"></a>
<div class="messages" id="error_class">
    <span id="error">{{ message }}</span>
</div>

<form action="updated" method="post">
    {% csrf_token %}
    <h2>Update your profile:</h2>
    <label>Your Student ID: {{ student.id }}</label>
    <input type="hidden" name="student_id" value="{{ student.id }}">
    <label>Your Email address: <br><span style="color: green; font-size: 120%;">{{ student.student_email }}</span></label>
    <label for="id_student_name">Update your name:</label>
    <input type="text" class="form-control" value="{{ student.student_name }}" name="student_name" id="id_student_name">
   
    {% if student.student_category == 'bachelor-of-arts' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Arts</label>
    {% elif student.student_category == 'bba/bms' %}
        <label for="id_category" style="color: green;">Selected: BBA/BMS</label>
    {% elif student.student_category == 'btech-bachelor-of-engg./tech' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Engg./Tech</label>
    {% elif student.student_category == 'bachelor-of-commerce' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Commerce</label>
    {% elif student.student_category == 'mbbs-bachelor-of-medicine' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Medicine</label>
    {% elif student.student_category == 'bachelor-of-science' %}
        <label for="id_category" style="color: green;">Selected: Bachelor of Science</label>
    {% elif student.student_category == 'intermediate' %}
        <label for="id_category" style="color: green;">Selected: Intermediate</label>
    {% elif student.student_category == 'ssc-10th-standard' %}
        <label for="id_category" style="color: green;">Selected: 10th-Standard</label>
    {% else %}
        <label for="id_category" style="color: green;">No category selected</label>
    {% endif %}

    <select name="student_category" id="id_student_category" class="form-select">
        <option value=0>select Category</option>
        <option value="bachelor-of-arts">Bachelor of Arts</option>
        <option value="bba/bms">BBA/BMS</option>
        <option value="btech-bachelor-of-engg./tech">Bachelor of Engg./Tech</option>
        <option value="bachelor-of-commerce">Bachelor of Commerce</option>
        <option value="mbbs-bachelor-of-medicine">Bachelor of Medicine</option>
        <option value="bachelor-of-science">Bachelor of Science</option>
        <option value="intermediate">Intermediate</option>
        <option value="ssc-10th-standard">10th-standard</option>
    </select>

    <button type="submit" class="btn btn-success" style="margin-top: 1em;">Update</button>
</form>

</section>

{% endblock %}